name: build binaries

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-16.04
    steps:
    - uses: ilammy/setup-nasm@v1
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: make
      working-directory: ./src
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: ect-ubuntu
        path: ect

  build-mac:
    runs-on: macos-10.15
    steps:
    - uses: ilammy/setup-nasm@v1
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: make
      working-directory: ./src
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: ect-mac
        path: ect

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: ilammy/setup-nasm@v1
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: make
      working-directory: ./src
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: ect-windows
        path: ect.exe
